[package]
name = "windows_app_api"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
quote = "1.0"
rayon = "1.5.1"
serde = "1.0.136"
windows-bindgen = { git = "https://github.com/microsoft/windows-rs" }
windows-metadata = { git = "https://github.com/microsoft/windows-rs" }
