[package]
name = "appwindow_sample"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies.windows]
version = "0.33.0"
features = [
    "alloc",
    "Foundation_Numerics",
    "UI_Composition",
    "UI_Core",
    "Graphics_Effects",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies.windows-app]
path = "../../../"
features = [
    "WindowsAppSdk_Foundation"
]

[dependencies.windows-app]
path = "../../../"
features = [
    "WindowsAppSdk_Foundation",
    "UI_Windowing",
]